/**
 * @file    tools/gen_golden_vectors.c
 * @brief   Host-side generator for tests/golden_vectors.h.
 *
 * @details
 *   Builds against the host reference backend (src/host/ + src/common/) and
 *   emits tests/golden_vectors.h: a curated set of input vectors for the
 *   per-family ASM LEAF primitives, each paired with the EXPECTED output
 *   computed by the host oracle (Tier-1-tested). The Tier-3 on-target
 *   self-test replays these through the real inline-asm backends on silicon
 *   and compares -- a regression in any backend shows up as the same vector
 *   index failing.
 *
 *   Scope: only the routines that have per-family inline asm (mul, divmod,
 *   add/sub, negate, bcd_add/sub). The C-over-asm wrappers (mul_s16,
 *   divmod_s16, BCD conversions) and the portable-C derived routines (sqrt,
 *   diff3, simpson38, rand) are validated by the exhaustive/randomized
 *   Tier-1 host tests; they share one C body across all backends, so there
 *   is no separate asm to verify on target. Keeping the on-target set to the
 *   asm leaves also fits the 8 K-word PIC16F87XA flash.
 *
 *   Run:  cmake -B build && cmake --build build
 *         ./build/gen_golden_vectors > tests/golden_vectors.h
 */

#include "pic_math.h"
#include <stdio.h>
#include <stddef.h>

static void hdr(void)
{
    printf("/**\n * @file    golden_vectors.h\n");
    printf(" * @brief   Curated input/expected-output vectors for the Tier-3\n");
    printf(" *          on-target self-test. AUTO-GENERATED by\n");
    printf(" *          tools/gen_golden_vectors.c (host oracle). Do not edit.\n");
    printf(" *\n");
    printf(" * @details Covers the per-family ASM leaf primitives only (the\n");
    printf(" *          C-over-asm and portable-C routines are Tier-1 host-tested).\n");
    printf(" *          Expected outputs are computed by the host reference backend.\n");
    printf(" */\n");
    printf("#ifndef PIC_MATH_GOLDEN_VECTORS_H\n");
    printf("#define PIC_MATH_GOLDEN_VECTORS_H\n\n");
    printf("#include <stdint.h>\n\n");
}

static void ftr(void) { printf("#endif /* PIC_MATH_GOLDEN_VECTORS_H */\n"); }

static void mul_u8(void)
{
    static const uint8_t a[] = {0,0x0C,0xFF,0x80};
    static const uint8_t b[] = {0,0x14,0xFF,0x80};
    printf("typedef struct { uint8_t a,b; uint16_t e; } gv_mul_u8_t;\n");
    printf("static const gv_mul_u8_t gv_mul_u8[] = {\n");
    for (int i = 0; i < 4; i++)
        printf("  {0x%02Xu,0x%02Xu,0x%04Xu},\n", a[i], b[i], pic_math_mul_u8(a[i], b[i]));
    printf("};\n#define GV_MUL_U8_N (sizeof(gv_mul_u8)/sizeof(gv_mul_u8[0]))\n\n");
}

static void mul_u16(void)
{
    static const uint16_t a[] = {1,0x0102,0xFFFF,0x8000};
    static const uint16_t b[] = {1,0x0103,0xFFFF,0x8000};
    printf("typedef struct { uint16_t a,b; uint32_t e; } gv_mul_u16_t;\n");
    printf("static const gv_mul_u16_t gv_mul_u16[] = {\n");
    for (int i = 0; i < 4; i++)
        printf("  {0x%04Xu,0x%04Xu,0x%08lXlu},\n", a[i], b[i], (unsigned long)pic_math_mul_u16(a[i], b[i]));
    printf("};\n#define GV_MUL_U16_N (sizeof(gv_mul_u16)/sizeof(gv_mul_u16[0]))\n\n");
}

static void mul_s16(void)
{
    static const int16_t a[] = {1,-258,INT16_MIN,-1};
    static const int16_t b[] = {1,259,-1,INT16_MIN};
    printf("typedef struct { int16_t a,b; int32_t e; } gv_mul_s16_t;\n");
    printf("static const gv_mul_s16_t gv_mul_s16[] = {\n");
    for (int i = 0; i < 4; i++)
        printf("  {%d,%d,%ldL},\n", a[i], b[i], (long)pic_math_mul_s16(a[i], b[i]));
    printf("};\n#define GV_MUL_S16_N (sizeof(gv_mul_s16)/sizeof(gv_mul_s16[0]))\n\n");
}

static void divmod_u16(void)
{
    struct { uint16_t n, d; } in[] = {{7,2},{0xFFFF,2},{0x8000,0x8000},{1234,0}};
    printf("typedef struct { uint16_t n,d,q,r; } gv_div_u16_t;\n");
    printf("static const gv_div_u16_t gv_div_u16[] = {\n");
    for (int i = 0; i < 4; i++) {
        pic_math_udiv16_t r = pic_math_divmod_u16(in[i].n, in[i].d, 0);
        printf("  {0x%04Xu,0x%04Xu,0x%04Xu,0x%04Xu},\n", in[i].n, in[i].d, r.quotient, r.remainder);
    }
    printf("};\n#define GV_DIV_U16_N (sizeof(gv_div_u16)/sizeof(gv_div_u16[0]))\n\n");
}

static void divmod_s16(void)
{
    struct { int16_t n, d; } in[] = {{-7,2},{7,-2},{INT16_MIN,-1},{1234,0}};
    printf("typedef struct { int16_t n,d,q,r; } gv_div_s16_t;\n");
    printf("static const gv_div_s16_t gv_div_s16[] = {\n");
    for (int i = 0; i < 4; i++) {
        pic_math_sdiv16_t r = pic_math_divmod_s16(in[i].n, in[i].d, 0);
        printf("  {%d,%d,%d,%d},\n", in[i].n, in[i].d, r.quotient, r.remainder);
    }
    printf("};\n#define GV_DIV_S16_N (sizeof(gv_div_s16)/sizeof(gv_div_s16[0]))\n\n");
}

static void divmod_u32_16(void)
{
    struct { uint32_t n; uint16_t d; } in[] = {{0x00020000u,1u},{0x00010506u,0x0103u},{1000u,0u}};
    printf("typedef struct { uint32_t n; uint16_t d,q,r; } gv_div_u32_16_t;\n");
    printf("static const gv_div_u32_16_t gv_div_u32_16[] = {\n");
    for (int i = 0; i < 3; i++) {
        pic_math_udiv16_t r = pic_math_divmod_u32_16(in[i].n, in[i].d, 0);
        printf("  {0x%08lXlu,0x%04Xu,0x%04Xu,0x%04Xu},\n", (unsigned long)in[i].n, in[i].d, r.quotient, r.remainder);
    }
    printf("};\n#define GV_DIV_U32_16_N (sizeof(gv_div_u32_16)/sizeof(gv_div_u32_16[0]))\n\n");
}

static void addsub(void)
{
    struct { uint16_t a,b; } in[] = {{0xFFFF,0x0002},{0x0002,0xFFFF},{0x8000,0x8000},{0,0}};
    printf("typedef struct { uint16_t a,b,r; uint8_t c; } gv_add_u16_t;\n");
    printf("static const gv_add_u16_t gv_add_u16[] = {\n");
    for (int i = 0; i < 4; i++) { bool c; uint16_t r = pic_math_add_u16(in[i].a, in[i].b, &c);
        printf("  {0x%04Xu,0x%04Xu,0x%04Xu,%u},\n", in[i].a, in[i].b, r, c?1u:0u); }
    printf("};\n#define GV_ADD_U16_N (sizeof(gv_add_u16)/sizeof(gv_add_u16[0]))\n\n");
    printf("typedef struct { uint16_t a,b,r; uint8_t b_out; } gv_sub_u16_t;\n");
    printf("static const gv_sub_u16_t gv_sub_u16[] = {\n");
    for (int i = 0; i < 4; i++) { bool bo; uint16_t r = pic_math_sub_u16(in[i].a, in[i].b, &bo);
        printf("  {0x%04Xu,0x%04Xu,0x%04Xu,%u},\n", in[i].a, in[i].b, r, bo?1u:0u); }
    printf("};\n#define GV_SUB_U16_N (sizeof(gv_sub_u16)/sizeof(gv_sub_u16[0]))\n\n");
}

static void negate(void)
{
    int16_t s[] = {0,5,INT16_MIN,-1};
    printf("typedef struct { int16_t v,e; } gv_neg_s16_t;\n");
    printf("static const gv_neg_s16_t gv_neg_s16[] = {\n");
    for (int i = 0; i < 4; i++) printf("  {%d,%d},\n", s[i], pic_math_negate_s16(s[i]));
    printf("};\n#define GV_NEG_S16_N (sizeof(gv_neg_s16)/sizeof(gv_neg_s16[0]))\n\n");
    int32_t l[] = {0,1,INT32_MIN,-123456789L};
    printf("typedef struct { int32_t v,e; } gv_neg_s32_t;\n");
    printf("static const gv_neg_s32_t gv_neg_s32[] = {\n");
    for (int i = 0; i < 4; i++) printf("  {%ldL,%ldL},\n", (long)l[i], (long)pic_math_negate_s32(l[i]));
    printf("};\n#define GV_NEG_S32_N (sizeof(gv_neg_s32)/sizeof(gv_neg_s32[0]))\n\n");
}

static void bcd_adjust(void)
{
    struct { uint8_t a, b; } ab[] = {{0x55,0x55},{0x12,0x34},{0x99,0x01},{0x00,0x00}};
    printf("typedef struct { uint8_t a,b,r; uint8_t c; } gv_bcd_add8_t;\n");
    printf("static const gv_bcd_add8_t gv_bcd_add8[] = {\n");
    for (int i = 0; i < 4; i++) { bool c; uint8_t r = pic_math_bcd_add8(ab[i].a, ab[i].b, &c);
        printf("  {0x%02Xu,0x%02Xu,0x%02Xu,%u},\n", ab[i].a, ab[i].b, r, c?1u:0u); }
    printf("};\n#define GV_BCD_ADD8_N (sizeof(gv_bcd_add8)/sizeof(gv_bcd_add8[0]))\n\n");
    printf("typedef struct { uint8_t a,b,r; uint8_t bo; } gv_bcd_sub8_t;\n");
    printf("static const gv_bcd_sub8_t gv_bcd_sub8[] = {\n");
    for (int i = 0; i < 4; i++) { bool bo; uint8_t r = pic_math_bcd_sub8(ab[i].a, ab[i].b, &bo);
        printf("  {0x%02Xu,0x%02Xu,0x%02Xu,%u},\n", ab[i].a, ab[i].b, r, bo?1u:0u); }
    printf("};\n#define GV_BCD_SUB8_N (sizeof(gv_bcd_sub8)/sizeof(gv_bcd_sub8[0]))\n\n");
}

int main(void)
{
    hdr();
    mul_u8(); mul_u16();
    divmod_u16(); divmod_u32_16();
    addsub(); negate(); bcd_adjust();
    ftr();
    return 0;
}