/**
 * @file    golden_vectors.h
 * @brief   Curated input/expected-output vectors for the Tier-3
 *          on-target self-test. AUTO-GENERATED by
 *          tools/gen_golden_vectors.c (host oracle). Do not edit.
 *
 * @details Covers the per-family ASM leaf primitives only (the
 *          C-over-asm and portable-C routines are Tier-1 host-tested).
 *          Expected outputs are computed by the host reference backend.
 */
#ifndef PIC_MATH_GOLDEN_VECTORS_H
#define PIC_MATH_GOLDEN_VECTORS_H

#include <stdint.h>

typedef struct { uint8_t a,b; uint16_t e; } gv_mul_u8_t;
static const gv_mul_u8_t gv_mul_u8[] = {
  {0x00u,0x00u,0x0000u},
  {0x0Cu,0x14u,0x00F0u},
  {0xFFu,0xFFu,0xFE01u},
  {0x80u,0x80u,0x4000u},
};
#define GV_MUL_U8_N (sizeof(gv_mul_u8)/sizeof(gv_mul_u8[0]))

typedef struct { uint16_t a,b; uint32_t e; } gv_mul_u16_t;
static const gv_mul_u16_t gv_mul_u16[] = {
  {0x0001u,0x0001u,0x00000001lu},
  {0x0102u,0x0103u,0x00010506lu},
  {0xFFFFu,0xFFFFu,0xFFFE0001lu},
  {0x8000u,0x8000u,0x40000000lu},
};
#define GV_MUL_U16_N (sizeof(gv_mul_u16)/sizeof(gv_mul_u16[0]))

typedef struct { int16_t a,b; int32_t e; } gv_mul_s16_t;
static const gv_mul_s16_t gv_mul_s16[] = {
  {1,1,1L},
  {-258,259,-66822L},
  {-32768,-1,32768L},
  {-1,-32768,32768L},
};
#define GV_MUL_S16_N (sizeof(gv_mul_s16)/sizeof(gv_mul_s16[0]))

typedef struct { uint16_t n,d,q,r; } gv_div_u16_t;
static const gv_div_u16_t gv_div_u16[] = {
  {0x0007u,0x0002u,0x0003u,0x0001u},
  {0xFFFFu,0x0002u,0x7FFFu,0x0001u},
  {0x8000u,0x8000u,0x0001u,0x0000u},
  {0x04D2u,0x0000u,0x0000u,0x0000u},
};
#define GV_DIV_U16_N (sizeof(gv_div_u16)/sizeof(gv_div_u16[0]))

typedef struct { int16_t n,d,q,r; } gv_div_s16_t;
static const gv_div_s16_t gv_div_s16[] = {
  {-7,2,-3,-1},
  {7,-2,-3,1},
  {-32768,-1,-32768,0},
  {1234,0,0,0},
};
#define GV_DIV_S16_N (sizeof(gv_div_s16)/sizeof(gv_div_s16[0]))

typedef struct { uint32_t n; uint16_t d,q,r; } gv_div_u32_16_t;
static const gv_div_u32_16_t gv_div_u32_16[] = {
  {0x00020000lu,0x0001u,0x0000u,0x0000u},
  {0x00010506lu,0x0103u,0x0102u,0x0000u},
  {0x000003E8lu,0x0000u,0x0000u,0x0000u},
};
#define GV_DIV_U32_16_N (sizeof(gv_div_u32_16)/sizeof(gv_div_u32_16[0]))

typedef struct { uint16_t a,b,r; uint8_t c; } gv_add_u16_t;
static const gv_add_u16_t gv_add_u16[] = {
  {0xFFFFu,0x0002u,0x0001u,1},
  {0x0002u,0xFFFFu,0x0001u,1},
  {0x8000u,0x8000u,0x0000u,1},
  {0x0000u,0x0000u,0x0000u,0},
};
#define GV_ADD_U16_N (sizeof(gv_add_u16)/sizeof(gv_add_u16[0]))

typedef struct { uint16_t a,b,r; uint8_t b_out; } gv_sub_u16_t;
static const gv_sub_u16_t gv_sub_u16[] = {
  {0xFFFFu,0x0002u,0xFFFDu,0},
  {0x0002u,0xFFFFu,0x0003u,1},
  {0x8000u,0x8000u,0x0000u,0},
  {0x0000u,0x0000u,0x0000u,0},
};
#define GV_SUB_U16_N (sizeof(gv_sub_u16)/sizeof(gv_sub_u16[0]))

typedef struct { int16_t v,e; } gv_neg_s16_t;
static const gv_neg_s16_t gv_neg_s16[] = {
  {0,0},
  {5,-5},
  {-32768,-32768},
  {-1,1},
};
#define GV_NEG_S16_N (sizeof(gv_neg_s16)/sizeof(gv_neg_s16[0]))

typedef struct { int32_t v,e; } gv_neg_s32_t;
static const gv_neg_s32_t gv_neg_s32[] = {
  {0L,0L},
  {1L,-1L},
  {-2147483648L,-2147483648L},
  {-123456789L,123456789L},
};
#define GV_NEG_S32_N (sizeof(gv_neg_s32)/sizeof(gv_neg_s32[0]))

typedef struct { uint8_t a,b,r; uint8_t c; } gv_bcd_add8_t;
static const gv_bcd_add8_t gv_bcd_add8[] = {
  {0x55u,0x55u,0x10u,1},
  {0x12u,0x34u,0x46u,0},
  {0x99u,0x01u,0x00u,1},
  {0x00u,0x00u,0x00u,0},
};
#define GV_BCD_ADD8_N (sizeof(gv_bcd_add8)/sizeof(gv_bcd_add8[0]))

typedef struct { uint8_t a,b,r; uint8_t bo; } gv_bcd_sub8_t;
static const gv_bcd_sub8_t gv_bcd_sub8[] = {
  {0x55u,0x55u,0x00u,0},
  {0x12u,0x34u,0x78u,1},
  {0x99u,0x01u,0x98u,0},
  {0x00u,0x00u,0x00u,0},
};
#define GV_BCD_SUB8_N (sizeof(gv_bcd_sub8)/sizeof(gv_bcd_sub8[0]))

#endif /* PIC_MATH_GOLDEN_VECTORS_H */
